spring:
  application:
    name: commerce-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/commerce?useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  cloud:
    stream:
      kafka:
        binder:
          brokers: infra-kafka.infra.svc.cluster.local:9092
      bindings:
        sales-in:
          destination: sales
          contentType: application/json
        sales-out:
          destination: sales
          contentType: application/json
server:
  port: 9017

security:
  jwt:
    key: ${JWT_AUTH}