spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce?useSSL=true&verifyServerCertificate=false&useCursorFetch=true
    username: root
    password: Ronaldo&7

  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka.devops:9092
      bindings:
        sales-in:
          destination: sales
          contentType: application/json
        sales-out:
          destination: sales
          contentType: application/json
dyball:
  apiKey: placeholder

ecoes:
  apiKey: placeholder

xo:
  apiKey: placeholder