kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "backend-service.fullname" . }}
data:
  application.yaml: |-
    spring:
      cloud:
        gateway:
          default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_LAST
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowCredentials: true
                allowedHeaders: "*"
          routes:
            - id: member-service
              uri: http://member-service:9014
              predicates:
                - Path=/api/member/**
              filters:
                - RewritePath=/api/(?<member>.*), /$\{member}