spring:
  application:
    name: gateway-service
  cloud:
    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_LAST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowCredentials: true
            allowedHeaders: "*"
      routes:
        - id: member-service
          uri: http://member-service:9014
          predicates:
            - Path=/v3/api/member/**
          filters:
            - RewritePath=/v3/api/(?<member>.*), /$\{member}

        - id: backoffice-service
          uri: http://backoffice-service:9015
          predicates:
            - Path=/v3/api/backoffice/**
          filters:
            - RewritePath=/v3/api/(?<backoffice>.*), /$\{backoffice}

        - id: commerce-service
          uri: http://commerce-service:9017
          predicates:
            - Path=/v3/api/commerce/**
          filters:
            - RewritePath=/v3/api/(?<commerce>.*), /$\{commerce}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

server:
  port: 8887
reactor:
  netty:
    http:
      server:
        accessLogEnabled=true: