apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "backend-service.fullname" . }}-configreader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "backend-service.fullname" . }}-configreader
subjects:
  - kind: ServiceAccount
    name: spectacle-service