{{- if .Values.database.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "backend-service.fullname" . }}-migration-job
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- end }}
